# permissions for end users to view jitsis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jitsi-viewer-role
rules:
- apiGroups:
  - apps.jit.si
  resources:
  - jitsis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.jit.si
  resources:
  - jitsis/status
  verbs:
  - get
